name: Schedule Scraping Job

on:
  workflow_dispatch:

jobs:
  scrape-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraping script
        run: |
          python -m listscraper -p 1~50 https://letterboxd.com/films/popular/this/year/ --concat

      - name: Commit and push updated data to the repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f scraper_outputs/
          git diff --cached --quiet || git commit -m "Update scraping results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
